### ISSUE TITLE
API container fails to start properly

### ISSUE THREAD

**Issue by jakubgs** [sartography/spiff-arena#532]
The `spiff.app-test` host API container refuses to respond to requests:
```
 > curl --silent --show-error "http://localhost:9000/v1.0/status"   
curl: (56) Recv failure: Connection reset by peer
```
At startup the API container gets stuck on this line for about 2 minutes:
```
Reinitialized existing Git repository in /app/process_models/.git/
```
Then shows this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/app/src/spiffworkflow_backend/services/logging_service.py", line 66, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/./bin/data_migrations/run_all.py", line 84, in <module>
    main()
  File "/app/./bin/data_migrations/run_all.py", line 75, in main
    run_version_2(process_instances)
  File "/app/./bin/data_migrations/run_all.py", line 21, in st_func
    r = func(*args, **kwargs)
  File "/app/./bin/data_migrations/run_all.py", line 56, in run_version_2
    Version2.run(process_instances)
  File "/app/src/spiffworkflow_backend/data_migrations/version_2.py", line 13, in run
    current_app.logger.info("process_instance_count: ", len(process_instances))
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/app/venv/lib/python3.11/site-packages/sentry_sdk/integrations/logging.py", line 96, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
Message: 'process_instance_count: '
Arguments: (986,)
```
And then the logs are full of `Failed to migrate process_instance` warnings:
```
{"level": "WARNING", "message": "Failed to migrate process_instance '11238'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:28.104Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '11870'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:29.001Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '11956'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:29.641Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '12428'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:30.071Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '12666'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:30.617Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '12667'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:31.036Z"}
{"level": "WARNING", "message": "Failed to migrate process_instance '12668'. The error was 'NoneType' object has no attribute '_child_added_notify'", "loggerName": "spiffworkflow_backend", "processName": "MainProcess", "processID": 21, "threadName": "MainThread", "threadID": 139653673092928, "timestamp": "2023-10-09T10:16:31.439Z"}
```
A lot of them.

**Comment by burnettk** [comment]
You caught us in the middle of testing a data migration. It wasn't going well. :) We have since changed the approach, and we no longer run the data migration in one fell swoop on app boot. Instead, we update each process instance on demand at the time when someone requests an operation that requires it. Closing this ticket, but let us know if anything seems off.
